[package]
name = "events-features"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
flate2 = "1.0.31"
zstd = "0.13.2"